name: PHP CS Fixer

on:
  push:
    branches:
      - main

jobs:
  php-cs-fixer:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - name: Install Composer dependencies
        run: |
          php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
          php composer-setup.php
          php -r "unlink('composer-setup.php');"
          mv composer.phar /usr/local/bin/composer
        working-directory: ${{ github.workspace }}

      - name: Install php-cs-fixer
        run: composer global require friendsofphp/php-cs-fixer

      - name: Run php-cs-fixer
        run: |
          ~/.composer/vendor/bin/php-cs-fixer fix --config=.php-cs-fixer.dist.php --verbose
          git config --global user.name "Your Name"
          git config --global user.email "you@example.com"
          git add .
          git diff-index --quiet HEAD || git commit -m "Fix coding standards with php-cs-fixer"
          git push https://$GH_TOKEN@github.com/${{ github.repository }}.git HEAD:main